name: Sync
version: %VERSION%
main: dev.heliosares.sync.spigot.SyncSpigot
description: Sync
api-version: 1.13
author: Heliosares
softdepend: [PremiumVanish]

commands:
    psync:
        usage: /psync
        description: Base command
    if:
        usage: /if
        description: Base command