name: Sync
version: 1.0
main: dev.heliosares.sync.spigot.SyncSpigot
description: Sync
api-version: 1.13
author: Heliosares

commands:
    psync:
        usage: /psync
        description: Base command