name: Sync
version: 1.1
main: dev.heliosares.sync.spigot.SyncSpigot
description: Sync
api-version: 1.13
author: Heliosares

commands:
    psync:
        usage: /psync
        description: Base command
    if:
        usage: /if
        description: Base command